name: CI/CD - Backend GKE Deployment

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: modern-saga-472703-k3
  GKE_CLUSTER: test-demo-cluster
  GKE_ZONE: us-central1-a
  IMAGE: gcr.io/modern-saga-472703-k3/backend-app

jobs:
  # -------------------------------
  # CI SECTION
  # -------------------------------

  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install flake8 pytest

  linting:
    name: Run Linting (flake8)
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: |
          flake8 app --max-line-length=120 --ignore=E302,E501

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v || true

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build Docker image
        run: docker build -t $IMAGE:${{ github.sha }} .

      - name: Save Docker image
        run: docker save $IMAGE:${{ github.sha }} -o backend-app.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app-image
          path: backend-app.tar

  trivy_scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app-image
          path: .

      - name: Load Docker image
        run: docker load -i backend-app.tar

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}:${{ github.sha }}
          format: 'table'
          exit-code: '0'

  push_artifacts:
    name: Push Image to GCR
    runs-on: ubuntu-latest
    needs: trivy_scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app-image
          path: .

      - name: Load Docker image
        run: docker load -i backend-app.tar

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Push Docker image
        run: |
          gcloud auth configure-docker gcr.io --quiet
          docker push $IMAGE:${{ github.sha }}
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:latest

  # -------------------------------
  # CD SECTION
  # -------------------------------
  deploy_gke:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: push_artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Install GKE auth plugin (Fixed)
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/ --validate=false
          kubectl set image deployment/backend-deployment backend=$IMAGE:${{ github.sha }}
          kubectl rollout status deployment/backend-deployment
          kubectl get svc backend-service -o wide
